add new method GetChat in proto
s21platform/chat-proto pull request #1
Opened 2024-12-09 09:43 UTC by LoskutovDaniil

2024-12-09 12:28 UTC, mikhail-kalugin requested changes

2024-12-09 12:28 UTC, Snegov1k commented on chat.proto
> +go_package = "./chat-proto";
должно начинаться с option 

По типу option go_package =

2024-12-09 12:28 UTC, Snegov1k commented on chat.proto
> +message GetGroupUUID {
Нужно немного подправить названия. Идет имя сообщения и, в зависимости данных, окончание In или Out

GetChatIn
GetChatOut

2024-12-09 14:42 UTC, alexseipopov commented
Обращу внимание, что в ПР только один файл, а по идее как минимум 4 должно быть - proto,  2 сгенерированныйх, и один README

2024-12-09 14:44 UTC, alexseipopov requested changes
оставил коммент в общей ленте ПР

2024-12-10 09:01 UTC, mikhail-kalugin approved these changes

2024-12-10 09:18 UTC, alexseipopov approved these changes

2024-12-10 09:26 UTC, merged